#!/usr/bin/env bash

function docker-exec-fzf() {
    if [ "$1" == "exec" ]; then
        docker exec -it "$(docker ps | awk '{print $NF}' | fzf --height 40% --reverse --border)" bash
    elif [ "$1" == "stop" ]; then
        docker stop "$(docker ps | awk '{print $NF}' | fzf --height 40% --reverse --border)"
    elif [ "$1" == "status" ]; then
        docker ps -a --format "{{.ID}} {{.Names}} {{.Status}}"
    elif [ "$1" == "list" ]; then
        docker ps | awk '{print $1, $NF}'
    else
        show-usage
    fi
}

function show-usage() {
    cat <<EOF
Usage: def [options]

Options:
  exec     Choose container to exec
  stop     Choose container to stop
  status   Show a list of container and status
  list     Show a list of container running
EOF
}

docker-exec-fzf $1
